services:
  fashion-store:
    build: 
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
    container_name: fashion-store
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    